In [1]:
# Model Development
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('automobileEDA.csv', header=0)
# header=0 specifies that the first row of the CSV file should be treated as 
# the header row, which contains the column names.

In [3]:
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

In [4]:
# Theory of Linear Regression and Multiple Linear Regression
# Simple Linear Regression
# Simple Linear Regression is a method to help us understand the relationship between two variables:

# The predictor/independent variable (X)
# The response/dependent variable (that we want to predict)(Y)
# The result of Linear Regression is a linear function that predicts the response (dependent) 
# variable as a function of the predictor (independent) variable.


In [5]:
# Loading the modules for linear regression
from sklearn.linear_model import LinearRegression

In [6]:
# Creating linear regression object
lm = LinearRegression()
lm

LinearRegression()

In [7]:
# using 'highway-mpg' to predict the price of the car using linear model 
X = df[['highway-mpg']]
Y = df[['price']]


In [8]:
# fitting the linear model using highway-mpg 
lm.fit(X,Y)

LinearRegression()

In [9]:
Yhat = lm.predict(X)
Yhat[0:5]

array([[16236.50464347],
       [16236.50464347],
       [17058.23802179],
       [13771.3045085 ],
       [20345.17153508]])

In [10]:
# finding the value of intercept(a)
lm.intercept_

array([38423.30585816])

In [11]:
# finding the value of slope(b)
lm.coef_

array([[-821.73337832]])

In [12]:
# creating a linear regression object called lm1
lm1 = LinearRegression()
lm1

LinearRegression()

In [14]:
# Traning the model using engine-size as the independent variable and price as dependent variable
X = df[['engine-size']]
Y = df[['price']]
lm1.fit(X,Y)


LinearRegression()

In [15]:
# finding the slope and intercept of the model
lm1.coef_

array([[166.86001569]])

In [16]:
lm1.intercept_

array([-7963.33890628])

In [17]:
# finding the equation of the predicted line 
# using X and Y  
Yhat=-7963.34 + 166.86*X

In [18]:
# using price as the dependent variable and engine size as the independent variable 
Price=-7963.34 + 166.86*df['engine-size']

In [ ]:
# Multiple Linear Regression
# What if we want to predict car price using more than one variable?

# If we want to use more variables in our model to predict car price, we can use Multiple Linear Regression. 
# Multiple Linear Regression is very similar to Simple Linear Regression, but this method is used to explain 
# the relationship between one continuous response (dependent) variable and two or more predictor (independent) 
# variables. Most of the real-world regression models involve multiple predictors.

In [19]:
# Developing a model using various variables as the predictor variables 
Z = df[['horsepower', 'curb-weight', 'engine-size', 'highway-mpg']]


In [20]:
# fitting the linear model using 4 variables
lm.fit(Z, df['price'])

LinearRegression()

In [21]:
lm.intercept_

-15806.62462632923

In [22]:
lm.coef_

array([53.49574423,  4.70770099, 81.53026382, 36.05748882])